In [38]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [39]:
df = pd.read_csv("Housing.csv")

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [21]:
print(df.shape)

df.info()

df.describe()

(545, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [22]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [40]:
categorical_columns = [
    'mainroad',
    'guestroom',
    'basement',
    'hotwaterheating',
    'airconditioning',
    'prefarea',
    'furnishingstatus'
]

encoder = LabelEncoder()

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0

In [41]:
X = df.drop("price", axis=1)
y = df["price"]

print(X.head())
print(y.head())

   area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0  7420         4          2        3         1          0         0
1  8960         4          4        4         1          0         0
2  9960         3          2        2         1          0         1
3  7500         4          2        2         1          0         1
4  7420         4          1        2         1          1         1

   hotwaterheating  airconditioning  parking  prefarea  furnishingstatus
0                0                1        2         1                 0
1                0                1        3         0                 0
2                0                0        2         1                 1
3                0                1        3         1                 0
4                0                1        2         0                 0
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
Name: price, dtype: int64

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", X_train.shape)
print("Testing samples :", X_test.shape)

Training samples: (436, 12)
Testing samples : (109, 12)

In [43]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [44]:
model = Sequential()

model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))

model.add(Dense(32, activation='relu'))

model.add(Dense(16, activation='relu'))

model.add(Dense(1, activation='linear'))

model.summary()

c:\Users\bhaka\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,457 (13.50 KB)

 Trainable params: 3,457 (13.50 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

In [31]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 25349383520256.0000 - mae: 4727422.0000 - val_loss: 24781588004864.0000 - val_mae: 4623896.5000
Epoch 2/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25349364645888.0000 - mae: 4727420.0000 - val_loss: 24781560741888.0000 - val_mae: 4623893.5000
Epoch 3/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25349318508544.0000 - mae: 4727416.0000 - val_loss: 24781485244416.0000 - val_mae: 4623886.0000
Epoch 4/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25349207359488.0000 - mae: 4727404.5000 - val_loss: 24781315375104.0000 - val_mae: 4623870.5000
Epoch 5/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25348968284160.0000 - mae: 4727381.5000 - val_loss: 24780956762112.0000 - val_mae: 4623837.5000
Epoch 6/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25348479647744.0000 - mae: 4727335.5000 - val_loss: 24780289867776.0000 - val_mae: 4623776.0000
Epoch 7/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25347573678080.0000 - mae: 4727251.5000 - val_loss: 24779130142720.0000 - val_mae: 4623670.5000
Epoch 8/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25346042757120.0000 - mae: 4727112.5000 - val_loss: 24777213345792.0000 - val_mae: 4623498.0000
Epoch 9/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25343618449408.0000 - mae: 4726890.5000 - val_loss: 24774279430144.0000 - val_mae: 4623236.5000
Epoch 10/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25339942141952.0000 - mae: 4726560.5000 - val_loss: 24769913159680.0000 - val_mae: 4622851.0000
Epoch 11/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25334619570176.0000 - mae: 4726079.5000 - val_loss: 24763711881216.0000 - val_mae: 4622307.5000
Epoch 12/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25327099183104.0000 - mae: 4725411.5000 - val_loss: 24755245678592.0000 - val_mae: 4621568.5000
Epoch 13/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25316705697792.0000 - mae: 4724508.0000 - val_loss: 24743956709376.0000 - val_mae: 4620588.5000
Epoch 14/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25303170678784.0000 - mae: 4723319.5000 - val_loss: 24728943198208.0000 - val_mae: 4619294.0000
Epoch 15/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25285443452928.0000 - mae: 4721762.0000 - val_loss: 24709699731456.0000 - val_mae: 4617643.0000
Epoch 16/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25263033286656.0000 - mae: 4719803.0000 - val_loss: 24685383254016.0000 - val_mae: 4615560.0000
Epoch 17/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25235126484992.0000 - mae: 4717369.0000 - val_loss: 24655477866496.0000 - val_mae: 4613009.5000
Epoch 18/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25200387162112.0000 - mae: 4714336.5000 - val_loss: 24619832573952.0000 - val_mae: 4609966.5000
Epoch 19/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25159306051584.0000 - mae: 4710786.0000 - val_loss: 24575337299968.0000 - val_mae: 4606193.5000
Epoch 20/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25110134128640.0000 - mae: 4706470.5000 - val_loss: 24522726047744.0000 - val_mae: 4601735.5000
Epoch 21/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25050577108992.0000 - mae: 4701279.0000 - val_loss: 24461642301440.0000 - val_mae: 4596548.0000
Epoch 22/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24980595146752.0000 - mae: 4695298.0000 - val_loss: 24391050067968.0000 - val_mae: 4590544.0000
Epoch 23/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24899439558656.0000 - mae: 4688351.5000 - val_loss: 24308264992768.0000 - val_mae: 4583517.0000
Epoch 24/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24806904823808.0000 - mae: 4680320.0000 - val_loss: 24213528248320.0000 - val_mae: 4575470.0000
Epoch 25/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24701858480128.0000 - mae: 4671143.0000 - val_loss: 24104713322496.0000 - val_mae: 4566232.5000
Epoch 26/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24579802136576.0000 - mae: 4660703.5000 - val_loss: 23986754813952.0000 - val_mae: 4556144.5000
Epoch 27/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24447383764992.0000 - mae: 4648998.5000 - val_loss: 23850047766528.0000 - val_mae: 4544470.5000
Epoch 28/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24294738362368.0000 - mae: 4635808.0000 - val_loss: 23699258343424.0000 - val_mae: 4531547.0000
Epoch 29/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24129321304064.0000 - mae: 4621068.5000 - val_loss: 23526413172736.0000 - val_mae: 4516730.5000
Epoch 30/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23936855179264.0000 - mae: 4604344.5000 - val_loss: 23345783373824.0000 - val_mae: 4501088.0000
Epoch 31/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23736780587008.0000 - mae: 4586598.5000 - val_loss: 23138150645760.0000 - val_mae: 4483147.0000
Epoch 32/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23511825383424.0000 - mae: 4566638.5000 - val_loss: 22915059810304.0000 - val_mae: 4463716.5000
Epoch 33/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23266437627904.0000 - mae: 4544837.0000 - val_loss: 22682103971840.0000 - val_mae: 4443214.0000
Epoch 34/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23008448086016.0000 - mae: 4521617.5000 - val_loss: 22425020399616.0000 - val_mae: 4420507.5000
Epoch 35/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22728073543680.0000 - mae: 4496191.5000 - val_loss: 22146816409600.0000 - val_mae: 4395673.5000
Epoch 36/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22421555904512.0000 - mae: 4468322.5000 - val_loss: 21856983711744.0000 - val_mae: 4369630.5000
Epoch 37/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22102165946368.0000 - mae: 4438946.0000 - val_loss: 21540301176832.0000 - val_mae: 4340884.5000
Epoch 38/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21755301199872.0000 - mae: 4406490.0000 - val_loss: 21205205647360.0000 - val_mae: 4310219.0000
Epoch 39/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21392537944064.0000 - mae: 4372240.0000 - val_loss: 20843579047936.0000 - val_mae: 4276722.5000
Epoch 40/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21002392174592.0000 - mae: 4334967.0000 - val_loss: 20469218541568.0000 - val_mae: 4241598.0000
Epoch 41/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20599548149760.0000 - mae: 4295962.5000 - val_loss: 20071967621120.0000 - val_mae: 4203830.0000
Epoch 42/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20172519768064.0000 - mae: 4254152.5000 - val_loss: 19665568923648.0000 - val_mae: 4164585.0000
Epoch 43/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19731746652160.0000 - mae: 4211023.5000 - val_loss: 19231271813120.0000 - val_mae: 4122048.7500
Epoch 44/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19268351557632.0000 - mae: 4163907.0000 - val_loss: 18785643790336.0000 - val_mae: 4077629.7500
Epoch 45/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18788776935424.0000 - mae: 4114112.7500 - val_loss: 18333137108992.0000 - val_mae: 4031533.0000
Epoch 46/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18302841651200.0000 - mae: 4063555.7500 - val_loss: 17852083994624.0000 - val_mae: 3981778.2500
Epoch 47/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17786678018048.0000 - mae: 4008400.2500 - val_loss: 17375997984768.0000 - val_mae: 3931331.7500
Epoch 48/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17273739804672.0000 - mae: 3952996.7500 - val_loss: 16876113494016.0000 - val_mae: 3877336.0000
Epoch 49/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16735745867776.0000 - mae: 3893227.0000 - val_loss: 16384666894336.0000 - val_mae: 3822755.2500
Epoch 50/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16203599839232.0000 - mae: 3832129.0000 - val_loss: 15868932128768.0000 - val_mae: 3764067.7500
Epoch 51/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15653179228160.0000 - mae: 3767485.0000 - val_loss: 15354273202176.0000 - val_mae: 3703979.0000
Epoch 52/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15103341625344.0000 - mae: 3701790.5000 - val_loss: 14831165898752.0000 - val_mae: 3641049.0000
Epoch 53/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14542972125184.0000 - mae: 3632212.2500 - val_loss: 14318105001984.0000 - val_mae: 3577455.7500
Epoch 54/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13993291808768.0000 - mae: 3562631.0000 - val_loss: 13798169640960.0000 - val_mae: 3510698.5000
Epoch 55/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13448232566784.0000 - mae: 3489100.7500 - val_loss: 13269305655296.0000 - val_mae: 3440819.0000
Epoch 56/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12899454025728.0000 - mae: 3414938.5000 - val_loss: 12764859858944.0000 - val_mae: 3371291.7500
Epoch 57/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12367633055744.0000 - mae: 3338300.0000 - val_loss: 12266447568896.0000 - val_mae: 3300020.2500
Epoch 58/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11844047601664.0000 - mae: 3261054.5000 - val_loss: 11778534670336.0000 - val_mae: 3227183.0000
Epoch 59/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11331918888960.0000 - mae: 3182707.2500 - val_loss: 11307337121792.0000 - val_mae: 3153995.0000
Epoch 60/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10838604775424.0000 - mae: 3105417.5000 - val_loss: 10847666569216.0000 - val_mae: 3079114.5000
Epoch 61/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10352474456064.0000 - mae: 3025428.5000 - val_loss: 10412724584448.0000 - val_mae: 3005352.7500
Epoch 62/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9899548344320.0000 - mae: 2946350.2500 - val_loss: 9986403991552.0000 - val_mae: 2929038.5000
Epoch 63/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9456393912320.0000 - mae: 2870410.7500 - val_loss: 9579850104832.0000 - val_mae: 2852637.7500
Epoch 64/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9032500772864.0000 - mae: 2797881.0000 - val_loss: 9199103770624.0000 - val_mae: 2777478.5000
Epoch 65/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8634572996608.0000 - mae: 2726152.7500 - val_loss: 8837981536256.0000 - val_mae: 2702360.5000
Epoch 66/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8257765638144.0000 - mae: 2653873.5000 - val_loss: 8503402430464.0000 - val_mae: 2629376.0000
Epoch 67/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7910439518208.0000 - mae: 2588090.7500 - val_loss: 8175879192576.0000 - val_mae: 2556543.0000
Epoch 68/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7580291694592.0000 - mae: 2523180.2500 - val_loss: 7873437892608.0000 - val_mae: 2488696.7500
Epoch 69/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7269375803392.0000 - mae: 2462836.5000 - val_loss: 7602333286400.0000 - val_mae: 2423841.7500
Epoch 70/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6988966133760.0000 - mae: 2407744.7500 - val_loss: 7338480631808.0000 - val_mae: 2363153.5000
Epoch 71/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6718922686464.0000 - mae: 2351717.7500 - val_loss: 7109146050560.0000 - val_mae: 2318976.5000
Epoch 72/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6479044673536.0000 - mae: 2300326.0000 - val_loss: 6886915047424.0000 - val_mae: 2280908.2500
Epoch 73/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6254653603840.0000 - mae: 2248198.0000 - val_loss: 6680724111360.0000 - val_mae: 2243045.5000
Epoch 74/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6044769058816.0000 - mae: 2199836.2500 - val_loss: 6493001220096.0000 - val_mae: 2206534.2500
Epoch 75/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5854769184768.0000 - mae: 2155238.0000 - val_loss: 6317855473664.0000 - val_mae: 2170591.7500
Epoch 76/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5672904163328.0000 - mae: 2113007.0000 - val_loss: 6167301455872.0000 - val_mae: 2139976.7500
Epoch 77/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5516358582272.0000 - mae: 2075074.6250 - val_loss: 6008817057792.0000 - val_mae: 2106307.7500
Epoch 78/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5357463142400.0000 - mae: 2035586.3750 - val_loss: 5871348744192.0000 - val_mae: 2076887.2500
Epoch 79/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5217523859456.0000 - mae: 1999894.6250 - val_loss: 5739897159680.0000 - val_mae: 2048017.8750
Epoch 80/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5084433350656.0000 - mae: 1967083.6250 - val_loss: 5619590889472.0000 - val_mae: 2022246.8750
Epoch 81/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4960487997440.0000 - mae: 1936752.7500 - val_loss: 5495923933184.0000 - val_mae: 1997243.5000
Epoch 82/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4841362948096.0000 - mae: 1907219.8750 - val_loss: 5382505234432.0000 - val_mae: 1973759.2500
Epoch 83/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4729988972544.0000 - mae: 1879813.0000 - val_loss: 5274971668480.0000 - val_mae: 1950792.0000
Epoch 84/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4626142724096.0000 - mae: 1854229.1250 - val_loss: 5172170326016.0000 - val_mae: 1927783.2500
Epoch 85/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4520115437568.0000 - mae: 1827507.8750 - val_loss: 5071978889216.0000 - val_mae: 1905088.5000
Epoch 86/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4423437778944.0000 - mae: 1802339.8750 - val_loss: 4975429681152.0000 - val_mae: 1882817.1250
Epoch 87/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4327321108480.0000 - mae: 1777125.1250 - val_loss: 4879665332224.0000 - val_mae: 1860783.2500
Epoch 88/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4236442599424.0000 - mae: 1752390.3750 - val_loss: 4788672528384.0000 - val_mae: 1838853.6250
Epoch 89/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4146086543360.0000 - mae: 1728384.7500 - val_loss: 4696470192128.0000 - val_mae: 1816576.7500
Epoch 90/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4059382415360.0000 - mae: 1705954.2500 - val_loss: 4608945553408.0000 - val_mae: 1795781.2500
Epoch 91/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3975580745728.0000 - mae: 1682746.6250 - val_loss: 4522824433664.0000 - val_mae: 1774431.8750
Epoch 92/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3892914159616.0000 - mae: 1659762.3750 - val_loss: 4438515253248.0000 - val_mae: 1753217.2500
Epoch 93/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3812147593216.0000 - mae: 1637398.6250 - val_loss: 4352192020480.0000 - val_mae: 1731293.5000
Epoch 94/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3732885471232.0000 - mae: 1616258.7500 - val_loss: 4270005420032.0000 - val_mae: 1710359.8750
Epoch 95/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3655241302016.0000 - mae: 1594551.8750 - val_loss: 4189914923008.0000 - val_mae: 1690562.7500
Epoch 96/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3579843182592.0000 - mae: 1574103.1250 - val_loss: 4110679539712.0000 - val_mae: 1670406.7500
Epoch 97/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3505911758848.0000 - mae: 1553893.5000 - val_loss: 4033766752256.0000 - val_mae: 1650223.1250
Epoch 98/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3433080553472.0000 - mae: 1534568.7500 - val_loss: 3957600026624.0000 - val_mae: 1629700.5000
Epoch 99/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3365045272576.0000 - mae: 1515741.8750 - val_loss: 3883657330688.0000 - val_mae: 1610208.7500
Epoch 100/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3292916613120.0000 - mae: 1496396.7500 - val_loss: 3809392984064.0000 - val_mae: 1589487.1250

In [46]:
loss, mae = model.evaluate(X_test, y_test)

print("Test Loss :", loss)
print("Test MAE  :", mae)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30129992499200.0000 - mae: 5007536.5000
Test Loss : 30129992499200.0
Test MAE  : 5007536.5

In [47]:
predictions = model.predict(X_test)

print(predictions[:5])

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
[[ 0.261633  ]
 [ 0.19252059]
 [-0.19035372]
 [ 0.12790605]
 [-0.0072246 ]]

In [48]:
rmse = np.sqrt(mean_squared_error(y_test, predictions))

print("RMSE :", rmse)

RMSE : 5489079.194368396

In [49]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": predictions.flatten()
})

comparison.head(10)

   Actual Price  Predicted Price
0       4060000         0.261633
1       6650000         0.192521
2       3710000        -0.190354
3       6440000         0.127906
4       2800000        -0.007225
5       4900000        -0.000444
6       5250000         0.214165
7       4543000         0.142467
8       2450000         0.082369
9       3353000        -0.117731

In [50]:
sample_house = [[
    6000,   # area
    3,      # bedrooms
    2,      # bathrooms
    2,      # stories
    1,      # mainroad (yes)
    0,      # guestroom (no)
    1,      # basement (yes)
    0,      # hotwaterheating (no)
    1,      # airconditioning (yes)
    2,      # parking
    1,      # prefarea (yes)
    2       # furnishingstatus (semi-furnished)
]]

sample_house = scaler.transform(sample_house)

predicted_price = model.predict(sample_house)

print("Predicted House Price:", predicted_price[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Predicted House Price: 0.033256594

c:\Users\bhaka\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(